### ISSUE TITLE
Column 'locale' doesn't exist in table

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#118]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_eua3)

**Comment by gilesp** [comment]
I can't read the "Front conversations" referenced in the initial post for this issue, but based on the title, I'm assuming it's the same issue I'm currently getting.

When upgrading to Craft 3, I get prompted to update the database twice. On the second time round, it fails with the following error:

```
Database Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'locale' doesn't exist in table
The SQL being executed was: ALTER TABLE craft_sproutseo_globals DROP COLUMN locale

Migration: barrelstrength\sproutseo\migrations\m180618_000001_globals_table

Output:

> add column siteId integer NOT NULL AFTER id to table {{%sproutseo_globals}} ... done (time: 0.025s)
> update in {{%sproutseo_globals}} ... done (time: 0.008s)
> create unique index craft_sproutseo_globals_id_siteId_idx on {{%sproutseo_globals}} (id,siteId) ... done (time: 0.016s)
> create unique index craft_sproutseo_globals_siteId_unq_idx on {{%sproutseo_globals}} (siteId) ... done (time: 0.017s)
> add foreign key craft_sproutseo_globals_siteId_fk: {{%sproutseo_globals}} (siteId) references {{%sites}} (id) ... done (time: 0.023s)
> drop column locale from table {{%sproutseo_globals}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1072 Key column 'locale' doesn't exist in table
The SQL being executed was: ALTER TABLE craft_sproutseo_globals DROP COLUMN locale (/var/www/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /var/www/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /var/www/vendor/yiisoft/yii2/db/Migration.php(392): yii\db\Command->execute()
#3 /var/www/vendor/barrelstrength/sprout-seo/src/migrations/m180618_000001_globals_table.php(55): yii\db\Migration->dropColumn('{{%sproutseo_gl...', 'locale')
#4 /var/www/vendor/craftcms/cms/src/db/Migration.php(56): barrelstrength\sproutseo\migrations\m180618_000001_globals_table->safeUp()
#5 /var/www/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#6 /var/www/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(barrelstrength\sproutseo\migrations\m180618_000001_globals_table))
#7 /var/www/vendor/craftcms/cms/src/services/Updates.php(216): craft\db\MigrationManager->up()
#8 /var/www/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(435): craft\services\Updates->runMigrations(Array)
#9 /var/www/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/www/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/www/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('migrate', Array)
#14 /var/www/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#15 /var/www/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('updater/migrate', Array)
#16 /var/www/vendor/craftcms/cms/src/web/Application.php(660): craft\web\Application->runAction('updater/migrate')
#17 /var/www/vendor/craftcms/cms/src/web/Application.php(236): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /var/www/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /var/www/web/index.php(21): yii\base\Application->run()
#20 {main}
```

However the table craft_sproutseo_globals does have a locale column, so I'm not sure why it's failing.

**Comment by BenParizek** [comment]
@gilesp Would you be able to send us your Craft 2 database? Or at least the `sproutseo_` tables so we can take a closer look?

**Comment by BenParizek** [comment]
@gilesp If you could send those over to sprout@barrelstrengthdesign.com we can see if we can identify what's going on. I agree with you it's odd that is failing when the conditional around that statement checks to see if the column exists first.

**Comment by BenParizek** [comment]
@gilesp As we haven't heard back from you and we haven't been able to recreate this issue on our end, we're going to close this ticket. If you are still experiencing the issue and you'd like to follow up with additional information, we'd be happy to re-open this thread and help troubleshoot further.
