### ISSUE TITLE
Potential unexpected redirect behavior

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-seo#156]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_j7j7)

**Comment by BenParizek** [comment]
```
2019-05-28 10:56:29 [-][51052][eeul9ecqkl8f15jkt17jctrvno][error][TypeError] TypeError: Argument 1 passed to craft\services\Assets::getAssetById() must be of the type integer, string given, called in /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/base/Schema.php on line 396 and defined in /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/services/Assets.php:112
Stack trace:
#0 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/base/Schema.php(396): craft\services\Assets->getAssetById('https://s3.amaz...')
#1 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/schema/ThingSchema.php(51): barrelstrength\sproutseo\base\Schema->addImage('image', 'https://s3.amaz...')
#2 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/schema/PersonSchema.php(48): barrelstrength\sproutseo\schema\ThingSchema->addProperties()
#3 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/base/Schema.php(153): barrelstrength\sproutseo\schema\PersonSchema->addProperties()
#4 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Extension/CoreExtension.php(1687): barrelstrength\sproutseo\base\Schema->getSchema()
#5 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/helpers/Template.php(79): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutseo\schema\PersonSchema), 'getSchema', Array, 'method', false, false)
#6 /sftpchroot-website.com/docroot/storage/runtime/compiled_templates/ad/ad5985dd134db684ac4880b3e87c06e1e780958bd3b01438dd887a13c0987ef3.php(200): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(barrelstrength\sproutseo\schema\PersonSchema), 'getSchema', Array, 'method')
#7 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(382): __TwigTemplate_bb8e6700443c0c42e2eca1b51a15f0601e62aa032354ca0bc423697262e08885->doDisplay(Array, Array)
#8 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#9 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#10 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#11 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#12 /sftpchroot-website.com/docroot/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#13 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#14 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('templates/_spec...', Array)
#15 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/services/Optimize.php(439): craft\web\View->renderTemplate('templates/_spec...', Array)
#16 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/services/Optimize.php(185): barrelstrength\sproutseo\services\Optimize->renderMetadata(Array)
#17 /sftpchroot-website.com/docroot/vendor/barrelstrength/sprout-seo/src/services/Optimize.php(100): barrelstrength\sproutseo\services\Optimize->getMetadata(Object(craft\elements\Entry), Object(craft\models\Site), true, Array)
#18 /sftpchroot-website.com/docroot/storage/runtime/compiled_templates/2d/2dd5e6f252e8727ac8f57950fa2819dbcf81921683fb2acc02dea0d03f0ccab1.php(82): barrelstrength\sproutseo\services\Optimize->getMetadataViaContext(Array)
#19 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(382): __TwigTemplate_fb76fce450fc830c3d1b48e81d52e7f47ff5095cb68005708c3e1d3eab51ba75->doDisplay(Array, Array)
#20 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#21 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#22 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#23 /sftpchroot-website.com/docroot/storage/runtime/compiled_templates/2f/2f70a129be77245f7adaeef6a3121d573b32bbefee3ee29d0de467609821c33e.php(46): craft\web\twig\Template->display(Array)
#24 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(382): __TwigTemplate_ca449fed781b612a6dcddaee5b4d3a5c3b5f7162c0c786096afb468c10cad805->doDisplay(Array, Array)
#25 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#26 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#27 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#28 /sftpchroot-website.com/docroot/storage/runtime/compiled_templates/d8/d8e530107f45dec00bc0e63bc1b8ad1682391696ce20dee992f6f2b48677ecc9.php(47): craft\web\twig\Template->display(Array, Array)
#29 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(382): __TwigTemplate_8a96d00e02cddd14b15ad2a3ae0b912c6d601b9272f75db4cc2d549cf48a028f->doDisplay(Array, Array)
#30 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#31 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#32 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#33 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#34 /sftpchroot-website.com/docroot/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#35 /sftpchroot-website.com/docroot/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#36 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('_views/peopleIn...', Array)
#37 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('_views/peopleIn...', Array)
#38 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('_views/peopleIn...', Array)
#39 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('_views/peopleIn...', Array)
#40 [internal function]: craft\controllers\TemplatesController->actionRender('_views/peopleIn...', Array)
#41 /sftpchroot-website.com/docroot/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#42 /sftpchroot-website.com/docroot/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#43 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#44 /sftpchroot-website.com/docroot/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#45 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#46 /sftpchroot-website.com/docroot/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#47 /sftpchroot-website.com/docroot/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#48 /sftpchroot-website.com/docroot/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#49 /sftpchroot-website.com/docroot/web/index.php(61): yii\base\Application->run()
```
