### ISSUE TITLE
Migration from Craft 2 to Craft 3 failing on sitemaps migration

### ISSUE THREAD

**Issue by marcdebiak** [barrelstrength/craft-sprout-seo#214]
### Description (screenshots, logs, ...)

Upgrading from Craft CMS 2.9.2, Sprout SEO 3.5.3 to Craft CMS 3.4.22.1

Migration fails with the following

```
TypeError: Return value of barrelstrength\sproutbasesitemaps\services\Settings::saveSitemapsSettings() must be of the type int, object returned

Migration: barrelstrength\sproutseo\migrations\m190415_000001_adds_sprout_sitemaps_migration

Output:

Exception: Return value of barrelstrength\sproutbasesitemaps\services\Settings::saveSitemapsSettings() must be of the type int, object returned (/home/ubuntu/sites/mooyah3.local/vendor/barrelstrength/sprout-base-sitemaps/src/services/Settings.php:45)
#0 /home/ubuntu/sites/mooyah3.local/vendor/barrelstrength/sprout-seo/src/migrations/m190415_000001_adds_sprout_sitemaps_migration.php(45): barrelstrength\sproutbasesitemaps\services\Settings->saveSitemapsSettings()
#1 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/db/Migration.php(52): barrelstrength\sproutseo\migrations\m190415_000001_adds_sprout_sitemaps_migration->safeUp()
#2 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up()
#3 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp()
#4 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#5 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations()
#6 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/controllers/pluginstore/InstallController.php(118): craft\controllers\BaseUpdaterController->runMigrations()
#7 [internal function]: craft\controllers\pluginstore\InstallController->actionMigrate()
#8 /home/ubuntu/sites/mooyah3.local/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#9 /home/ubuntu/sites/mooyah3.local/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#10 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction()
#11 /home/ubuntu/sites/mooyah3.local/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#12 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction()
#13 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction()
#14 /home/ubuntu/sites/mooyah3.local/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic()
#15 /home/ubuntu/sites/mooyah3.local/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#16 /home/ubuntu/sites/mooyah3.local/web/index.php(22): yii\base\Application->run()
#17 {main}
```

### Steps to reproduce

1. run `composer require barrelstrength/sprout-seo`
2. Visit CP to run the migration

### Additional info

- Craft version: 3.4.22.1
- PHP version: 7.4
- Database driver & version:  MySQL 5.7
- Plugins & versions: Sprout SEO 3.5.3 to 4.6.3

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@marcdebiak This should be fixed now. Can you delete Sprout SEO from composer and re-require it? The fix is in one of its dependencies so you'll need it to pull in barrelstrength/sprout-base-sitemaps:v1.4.1 to get address the migration issue.

**Comment by marcdebiak** [comment]
@BenParizek that worked for me. Thank you!
